apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - networkpolicy-ingress.yaml
  - networkpolicy-core-egress.yaml
  - networkpolicy-internal-egress.yaml
  - networkpolicy-apiserver-egress.yaml
  - networkpolicy-external-egress.yaml
