"""Deterministic telemetry fixtures for admin-console tests."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

from admin_console.domain import (
    ActivityEvent,
    AttributionLevel,
    TriggerKind,
)


def _at(minutes_ago: int) -> datetime:
    anchor = datetime.now(UTC).replace(second=0, microsecond=0)
    return anchor - timedelta(minutes=minutes_ago)


class FixtureTelemetryProvider:
    """Representative activity with explicit human and autonomous chains."""

    def list_activity(self) -> list[ActivityEvent]:
        return [
            ActivityEvent(
                "evt-001",
                _at(8),
                "int-7f21",
                TriggerKind.HUMAN,
                "message",
                "Investigate checkout latency",
                "completed",
                "Alice asked the Chat Agent to investigate checkout latency.",
                "chat",
                platform="web",
                user_id="alice@example.com",
                session_id="web-4c12",
                attribution=AttributionLevel.EXPLICIT,
                trace_id="7f21a001",
            ),
            ActivityEvent(
                "evt-002",
                _at(7),
                "int-7f21",
                TriggerKind.HUMAN,
                "delegation",
                "Route fleet investigation",
                "completed",
                "Chat Agent delegated the request to the Platform Agent.",
                "chat",
                platform="web",
                user_id="alice@example.com",
                session_id="web-4c12",
                task_id="task-a91c",
                duration_ms=310,
                attribution=AttributionLevel.EXPLICIT,
                trace_id="7f21a001",
            ),
            ActivityEvent(
                "evt-003",
                _at(6),
                "int-7f21",
                TriggerKind.HUMAN,
                "delegation",
                "Inspect production cluster",
                "completed",
                "Platform Agent delegated runtime diagnosis to cluster-prod-us.",
                "platform",
                platform="web",
                user_id="alice@example.com",
                session_id="web-4c12",
                task_id="task-b31d",
                parent_task_id="task-a91c",
                cluster="prod-us",
                duration_ms=520,
                attribution=AttributionLevel.INHERITED,
                trace_id="7f21a001",
            ),
            ActivityEvent(
                "evt-004",
                _at(5),
                "int-7f21",
                TriggerKind.HUMAN,
                "tool",
                "Query pod metrics",
                "completed",
                "Read CPU and memory metrics for checkout workloads.",
                "cluster-prod-us",
                platform="web",
                user_id="alice@example.com",
                session_id="web-4c12",
                task_id="task-b31d",
                parent_task_id="task-a91c",
                tool_name="kubectl top",
                cluster="prod-us",
                namespace="checkout",
                resource="Deployment/checkout-api",
                duration_ms=1840,
                attribution=AttributionLevel.INHERITED,
                trace_id="7f21a001",
            ),
            ActivityEvent(
                "evt-005",
                _at(4),
                "int-7f21",
                TriggerKind.HUMAN,
                "tool",
                "Read latency traces",
                "completed",
                "Found elevated payment-provider latency on the critical path.",
                "cluster-prod-us",
                platform="web",
                user_id="alice@example.com",
                session_id="web-4c12",
                task_id="task-b31d",
                parent_task_id="task-a91c",
                tool_name="Cloud Trace",
                cluster="prod-us",
                namespace="checkout",
                resource="Service/checkout-api",
                duration_ms=3260,
                attribution=AttributionLevel.INHERITED,
                trace_id="7f21a001",
            ),
            ActivityEvent(
                "evt-006",
                _at(3),
                "int-7f21",
                TriggerKind.HUMAN,
                "outcome",
                "Return diagnosis",
                "completed",
                "Reported the external dependency bottleneck with a Trace link.",
                "platform",
                platform="web",
                user_id="alice@example.com",
                session_id="web-4c12",
                task_id="task-a91c",
                duration_ms=12_400,
                attribution=AttributionLevel.EXPLICIT,
                trace_id="7f21a001",
            ),
            ActivityEvent(
                "evt-007",
                _at(42),
                "int-c820",
                TriggerKind.EVENT,
                "event",
                "CrashLoopBackOff detected",
                "completed",
                "The Kubernetes event watcher opened an autonomous investigation.",
                "event-watcher",
                platform="kubernetes",
                session_id="k8s-evt-c820",
                cluster="staging-eu",
                namespace="catalog",
                resource="Deployment/catalog-worker",
                attribution=AttributionLevel.EXPLICIT,
                trace_id="c820b114",
            ),
            ActivityEvent(
                "evt-008",
                _at(40),
                "int-c820",
                TriggerKind.EVENT,
                "tool",
                "Inspect pod failures",
                "completed",
                "Identified an invalid environment variable after rollout.",
                "cluster-staging-eu",
                platform="kubernetes",
                session_id="k8s-evt-c820",
                task_id="task-d882",
                tool_name="kubectl describe",
                cluster="staging-eu",
                namespace="catalog",
                resource="Pod/catalog-worker-7f8c",
                duration_ms=970,
                attribution=AttributionLevel.INHERITED,
                trace_id="c820b114",
            ),
            ActivityEvent(
                "evt-009",
                _at(38),
                "int-c820",
                TriggerKind.EVENT,
                "notification",
                "Notify on-call channel",
                "completed",
                "Posted a concise diagnosis to the configured home channel.",
                "platform",
                platform="google_chat",
                session_id="k8s-evt-c820",
                task_id="task-d882",
                cluster="staging-eu",
                namespace="catalog",
                attribution=AttributionLevel.INHERITED,
                trace_id="c820b114",
            ),
            ActivityEvent(
                "evt-010",
                _at(75),
                "int-5db0",
                TriggerKind.CRON,
                "cron",
                "Fleet policy sweep",
                "completed",
                "Scheduled governance scan checked namespace isolation.",
                "platform",
                platform="cron",
                session_id="cron-policy-sweep",
                attribution=AttributionLevel.EXPLICIT,
                trace_id="5db0c991",
            ),
            ActivityEvent(
                "evt-011",
                _at(72),
                "int-5db0",
                TriggerKind.CRON,
                "tool",
                "List NetworkPolicies",
                "completed",
                "Read network policy coverage across managed namespaces.",
                "platform",
                platform="cron",
                session_id="cron-policy-sweep",
                task_id="task-f10a",
                tool_name="gcloud container fleet",
                duration_ms=4420,
                attribution=AttributionLevel.INHERITED,
                trace_id="5db0c991",
            ),
            ActivityEvent(
                "evt-012",
                _at(70),
                "int-5db0",
                TriggerKind.CRON,
                "outcome",
                "Record policy finding",
                "blocked",
                "Two namespaces lack default-deny policies; awaiting owner input.",
                "platform",
                platform="cron",
                session_id="cron-policy-sweep",
                task_id="task-f10a",
                attribution=AttributionLevel.INHERITED,
                trace_id="5db0c991",
            ),
            ActivityEvent(
                "evt-013",
                _at(112),
                "int-11ab",
                TriggerKind.HUMAN,
                "message",
                "Show staging capacity",
                "completed",
                "Bob requested a capacity summary in Google Chat.",
                "chat",
                platform="google_chat",
                user_id="bob@example.com",
                session_id="gchat-11ab",
                attribution=AttributionLevel.EXPLICIT,
                trace_id="11ab0193",
            ),
            ActivityEvent(
                "evt-014",
                _at(110),
                "int-11ab",
                TriggerKind.HUMAN,
                "tool",
                "Read cluster utilization",
                "failed",
                "Metrics query exceeded its deadline and was retried.",
                "cluster-staging-us",
                platform="google_chat",
                user_id="bob@example.com",
                session_id="gchat-11ab",
                task_id="task-91ef",
                tool_name="Cloud Monitoring",
                cluster="staging-us",
                duration_ms=10_000,
                attribution=AttributionLevel.INFERRED,
                trace_id="11ab0193",
            ),
            ActivityEvent(
                "evt-015",
                _at(109),
                "int-11ab",
                TriggerKind.RETRY,
                "tool",
                "Retry cluster utilization",
                "completed",
                "Retry returned the requested utilization snapshot.",
                "cluster-staging-us",
                platform="google_chat",
                user_id="bob@example.com",
                session_id="gchat-11ab",
                task_id="task-91ef",
                tool_name="Cloud Monitoring",
                cluster="staging-us",
                duration_ms=2190,
                attribution=AttributionLevel.INFERRED,
                trace_id="11ab0193",
            ),
            ActivityEvent(
                "evt-016",
                _at(150),
                "int-unknown",
                TriggerKind.AGENT_FOLLOWUP,
                "tool",
                "Refresh inventory cache",
                "completed",
                "Legacy activity lacks a reliable originating session.",
                "platform",
                tool_name="gcloud asset search",
                duration_ms=880,
                attribution=AttributionLevel.MISSING,
            ),
        ]
