apiVersion: v1
kind: ConfigMap
metadata:
  name: github-token-minter-config
data:
  ${GITHUB_ORG}-${GITHUB_REPO}.yaml: |
    version: 'minty.abcxyz.dev/v2'
    rule:
      if: "assertion.iss == 'https://container.googleapis.com/v1/projects/${PROJECT_ID}/locations/${REGION}/clusters/${CLUSTER}'"
    scope:
      platform-agent-scope:
        rule:
          if: "assertion.sub == 'system:serviceaccount:agent-system:platform-agent'"
        repositories:
          - '${GITHUB_REPO}'
        permissions:
          contents: 'write'
          pull_requests: 'write'
