apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-token-minter-ksa
  annotations:
    iam.gke.io/gcp-service-account: github-token-minter-sa@${PROJECT_ID}.iam.gserviceaccount.com
automountServiceAccountToken: false
