apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../platform
  - fqdn-networkpolicy.yaml

patches:
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: platform-agent-external-egress
        namespace: kubeagents-system
      $patch: delete
