name: Staging Redeploy Agent

on:
  push:
    tags:
      - "staging/**"

concurrency:
  group: staging-redeploy-agent
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  call-deploy:
    if: github.repository == 'gke-labs/kube-agents'
    uses: ./.github/workflows/reusable-deploy-agent.yml
    with:
      target_environment: "staging"
      image_tag: ${{ github.sha }}
      checkout_sha: ${{ github.sha }}
